### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by arsalanNasiri** [chabokpush/chabok-demo-android#13]
com.adpdigital.push.AdpPushClient: Cannot save device, Reason: Internal Server Error
    org.apache.http.client.HttpResponseException: Internal Server Error
        at a.f.sendResponseMessage(SourceFile:440)
        at a.e.run(SourceFile:2078)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)

**Comment by Husseinhj** [comment]
Please, **explain** more about this error, When this error happens?
Did you connect to a **VPN**?
Is your device **connected** to the internet?

Note: Please add `code` or `errors` to **Code tag**.
