### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by arsalanNasiri** [chabokpush/chabok-demo-android#18]
```
Fatal Exception: java.lang.NullPointerException
       at com.adpdigital.push.PushService$b.getService(SourceFile:1409)
       at com.adpdigital.push.c.onServiceConnected(SourceFile:745)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1131)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1148)
       at android.os.Handler.handleCallback(Handler.java:800)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5371)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by Husseinhj** [comment]
<p dir="rtl">چه زمانی این خطا رو میگیرید؟ لطفا اطلاع بیشتری در اختیار ما قرار بدید</p>

**Comment by arsalanasanbar** [comment]
واقعیتش من خودم نمی دونم من اینو  لاگ های فایربیس بررسی می گردم  دیدم

**Comment by Husseinhj** [comment]
منظور شما این هست که کرش ریپورت شما این رو گزارش داده؟
برای چه نسخه‌های اندروید و چند درصد از خطاهای شماست؟

**Comment by arsalanasanbar** [comment]
بله منظورم کرش ریپورت هستش 
4.2.2,5,6,7 اندروید

**Comment by Husseinhj** [comment]
<p dir="rtl">لطفا کد مربوط به اجرا سرویس رو برای ما اینجا قرار بدید تا بررسی کنیم. @arsalanasanbar </p>

**Comment by Husseinhj** [comment]
<p dir="rtl">این مشکل قبلا در <a href="https://github.com/chabokpush/chabok-client-android/issues/15">issue</a> ریپازیتوری اندروید مطرح شده و در نسخه ۲.۱۳.۲ این مورد حل شده است.</p>
